### ISSUE TITLE
about frontend and backend

### ISSUE THREAD

**Issue by kolapapa** [oleg-agapov/flask-vue-spa#1]
when i running backend prodject and fronted project like : 
`python run.py`
`npm run dev`

how to it work? I want real-time change i can change my code

> I have an idea is using requests to get the localhost:8080/app.js and html but its too trouble

**Comment by oleg-agapov** [comment]
@kolapapa 
In development you will have two servers running simultaneously. 
First server is Flask itself, you run it with `python run.py` or `flask run`. It has address `localhost:5000`.
Second server is Node.js which comes with Webpack which allows you to see real-time changes. You run it with `npm run dev` and it has address `localhost:8080`.
Vue.js application communicate with Flask server through Axios library. By default this communication is not allowed because Flask is closed to request from another servers (in our case it's Node.js). That is why we enabled this by utilizing CORS library.
When you finish your front-end app you can build a static html/css/js files and serve them over Flask.

**Comment by kolapapa** [comment]
@oleg-agapov 
emmm..
I want  visit `localhost:5000` (flask address), I mean backend to control frontend...
When I do this, frontend project must have `npm run build`=> `/dist/index.html`+`/dist/static`+ blahblahblah

I don't know. Did I make it clear?

**Comment by oleg-agapov** [comment]
@kolapapa 
Not really understand what kind of control you want to have, sorry.

I want to achieve two goals in this project:
1) I want to have single page application having Vue.js on board. It has vue-router to create views and axios to communicate with APIs
2) I want to have Flask API server so I can do a requests to it from Vue.js app

In order to maintain only one server in Production I decided to create static assets from Vue.js application and point my Flask server to them. So, yes, first of all I need to run `npm run build`. This will create a `/dist` folder. And then I point out Flask to this folder, so it serves them.

**Comment by kolapapa** [comment]
@oleg-agapov
yep! so，in the end , you will run flask server . 
when i debug frontend project and run flask server(must have /dist folder) ,the frontend is npm run dev to running , webpack will build html,js... in the RAM ,so dont have /dist folder

**Comment by oleg-agapov** [comment]
@kolapapa you don't need compiled `/dist` folder while debugging/developing. You still can do a requests to Flask server from front-end because there is CORS enabled. Don't worry if during development you don't have `/dist` folder, you need build it only for production.

You could possibly create a config in Webpack to have `/dist` folder automatically rebuild after you do changes to your source code. But this will add significant overload and you'll have to wait until it recompile all code into html/css/js (as you see `dev` server recompile code almost immediately, but `build` command requires a lot more time).

**Comment by oleg-agapov** [comment]
@kolapapa check this Issue https://github.com/oleg-agapov/flask-vue-spa/issues/2
Maybe it's what you wanted

**Comment by kolapapa** [comment]
@oleg-agapov yep,The same with me.
```python
@bp.route('/', methods=['GET'])
@require_auth
def index():
    if CONF.debug:
        return requests.get('http://localhost:8080/').text
    else:
        return render_template('index.html')

@bp.route('/app.js')
def app_js():
    return requests.get('http://localhost:8080/app.js').text
```
